-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.client
(

    CONSTRAINT client_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public.client_job
(

    CONSTRAINT client_job_pkey PRIMARY KEY (client_job_id)
);

CREATE TABLE IF NOT EXISTS public.client_va
(

    CONSTRAINT client_va_pkey PRIMARY KEY (client_va_id)
);

CREATE TABLE IF NOT EXISTS public.job
(

    CONSTRAINT job_pkey PRIMARY KEY (job_id)
);

CREATE TABLE IF NOT EXISTS public.job_skill
(

    CONSTRAINT job_skill_pkey PRIMARY KEY (job_skill_id)
);

CREATE TABLE IF NOT EXISTS public.skill
(

    CONSTRAINT skill_pkey PRIMARY KEY (skill_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
)
;

CREATE TABLE IF NOT EXISTS public.va
(

    CONSTRAINT va_pkey PRIMARY KEY (va_id)
);

CREATE TABLE IF NOT EXISTS public.va_skill
(

    CONSTRAINT va_skill_pkey PRIMARY KEY (va_skill_id)
);

ALTER TABLE IF EXISTS public.client_job
    ADD CONSTRAINT client_job_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES public.client (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.client_job
    ADD CONSTRAINT client_job_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES public.job (job_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.client_va
    ADD CONSTRAINT "client_va_client_ID_fkey" FOREIGN KEY ("client_ID")
    REFERENCES public.client (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.client_va
    ADD CONSTRAINT "client_va_va_ID_fkey" FOREIGN KEY ("va_ID")
    REFERENCES public.va (va_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.job_skill
    ADD CONSTRAINT job_skill_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES public.job (job_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.job_skill
    ADD CONSTRAINT job_skill_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES public.skill (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.va_skill
    ADD CONSTRAINT va_skill_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES public.skill (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.va_skill
    ADD CONSTRAINT va_skill_va_id_fkey FOREIGN KEY (va_id)
    REFERENCES public.va (va_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;